### ISSUE TITLE
Pagefind UI: close results on escape keydown in search input

### ISSUE THREAD

**Issue by whyboris** [CloudCannon/pagefind#124]
It feels rather intuitive to press `esc` to close the results, so I think it would be nice to add that feature.

Additionally, it seems like clicking outside of the search (_input_ or the _drawer_) should close the search results 🤔 though that may be best left to an optional setting when initiating _pagefind_ 🤷‍♂️ 

I've never worked with _Svelte_ but it seems relatively easy to add this functionality: [example code](https://svelte.dev/repl/08a2a569d1354426ab747445ece60fcb?version=3.22.2)

Seems like it's just a matter of adding some of the code to the [ui.svelte](https://github.com/CloudCannon/pagefind/blob/main/pagefind_ui/svelte/ui.svelte) file 🤔 

If you think it's easy enough for a newcomer to create a PR, I could give it a try 😅 though of course it's easier if someone else does it 😉

**Comment by bglw** [comment]
I'm on board with adding handling for `esc` to close the search results, if the search field is actively focused.

In terms of any wider focus handling / closing results, I know people use the current UI in many contexts and I would like to avoid this UI widget doing nay of that work, to keep it as generic as possible (and avoid having too many options/features in one widget).

I have loose plans of moving beyond having one official UI, and instead a library of official and/or community UI widgets that could be used, so that kind of feature would be great for a specific UI widget that was designed for a modal or dropdown-style search experience.

I'm open to a PR for the `esc` handling, but I'm happy to implement it the nest time I'm in that file so no pressure!

**Comment by jmichelgarcia** [comment]
This is one of the few things stopping me from switching from Lunr.js to Pagefind in a Docsy website used by my company.

**Comment by bglw** [comment]
Hi @whyboris & @jmichelgarcia — this is now implemented (alongside some other goodies) in [v0.11.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.11.0) :)
