### ISSUE TITLE
Making bundle-dir absolute?

### ISSUE THREAD

**Issue by chrisspen** [CloudCannon/pagefind#138]
The [docs](https://pagefind.app/docs/config-options/#bundle-directory) state that bundle-dir is relative to the input path.

I'm finding this very awkward, as my source file directory and pagefind index directory are in very different places. That makes calculating the relative path to use to get from one to the other a bit complicated and unintuitive.

Is there any way to make bundle-dir absolute? I've tried giving it an absolute path, but that just seems to send the data to nowhere.

**Comment by bglw** [comment]
👋 Some discussion of this in #68 — since I'm hearing more about this it's definitely more confusing than it needs to be (the tricky thing being the exact inverse also has some complications)

Since that thread I have had more thoughts on how to improve this, I don't think the two arguments are necessarily the best path forward, but in any case I am saving that more holistic change for a larger Pagefind 1.0 release & migration.

I think for this case in particular I can tweak the behavior of `--bundle-dir` to use a fully absolute path that starts with `/`, since that is fairly unambiguous. Does that work for you?

**Comment by chrisspen** [comment]
Yeah, treating a leading `/` as absolute would help, and be a bit more intuitive. That can coexist with the existing functionality.

**Comment by bglw** [comment]
Hmm, I've just [tested passing an absolute path](https://github.com/CloudCannon/pagefind/blob/ed1950659a792f4ebcd5a83c011587897fbd17d4/pagefind/features/build_options.feature#L64-L93) to `--bundle-dir` and it's already working as described.

Can you share the exact config file / command you're running? (And os/arch details if unusual)

**Comment by chrisspen** [comment]
You're right. I created a MRE and found it worked correctly, so it must be some issue in my application's setup.
