### ISSUE TITLE
JSON Compatibility

### ISSUE THREAD

**Issue by ng-druid** [CloudCannon/pagefind#142]
We store our data on Github repos using json. Would this search be compatible with this?

Use case would be given several services here could page find be used to search for a service by domain?

https://github.com/rollthecloudinc/hedge-objects-prod/tree/master/services

**Comment by bglw** [comment]
👋 Hello!

Hmm, good question. It's something that Pagefind has avoided supporting til now — the focus has been on the parts of a static site that can be indexed with low/no config. JSON files are harder, since the files themselves cannot be tagged in any way, and they don't have standardised metadata, any data file support would require more configuration than the current baseline.

I won't rule it out, but I will likely wait for a few more use cases pop up before implementing anything — if others are hitting this limitation please drop some comments on the issue.

If anyone has some good ideas for a low-config way to support this out of the box I'm all ears!

**Comment by ng-druid** [comment]
@bglw ok, that makes sense and is kind of what I gathered from the docs. We use Opensearch but someone on a forum mentioned this as possible lightweight tool for searches without costs attached like Opensearch.

**Comment by bglw** [comment]
Update — this will be supported via #72 which is underway — see the comment there for details 🙂

**Comment by ng-druid** [comment]
@bglw Awesome – Now we can offer a free search solution against JSON stored in our climate aware database on Github repositories.

**Comment by bglw** [comment]
Hey @ng-druid  ! 👋

Good news — this has landed in Pagefind v1.0.0! ✨

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙

See the new docs on [using the Node API](https://pagefind.app/docs/node-api/), which should open the door for you. Feel free to ping me here if you have any questions!
