### ISSUE TITLE
Pagefind uses incorrect link text for all results. Pulls the text from a modal box instead of actual page.

### ISSUE THREAD

**Issue by justsilencia** [CloudCannon/pagefind#179]
I have a strange issue where all of the correct results are being found and displayed. However, pagefind is inserting the text from an h1 tag found within a modal box in the navbar into the anchor tag of the pagefind search result. 

So all the result links have the same text, in this case: 'Coming Soon!'

All of the results are correct, just not the link text. The link works as expected so the route is good.

I've made a [test repo here](https://github.com/justsilencia/pagefind-troubleshoot)

And here's a link to the actual [site hosted on netlify](https://pagefind-troubleshoot.netlify.app/). Just type the letter "a" into the search, and you will see the results as I explained above. The modal box I mentioned can be seen by clicking the profile icon on the right side of the navbar.

As a side note, I am using data-pagefind-body attribute, so the selection is limited.

Much appreciated!

**Comment by bglw** [comment]
Yes, this is a small (but intentional) quirk of how everything interacts — I need to do another pass over the documentation to make this super clear.

The `data-pagefind-body` tag only limits the search indexing, it doesn't limit getting metadata from the page. Many people tag just a post body as the search index, and the title/image sits outside this. Similarly, people tag metadata and filters inside their `<head>`, which is implicitly output the search index element.

The page title is fetched via the [Metadata process](https://pagefind.app/docs/metadata/), so there are two ways you can change this behavior on a site:

1. If you explicitly tag an element as the `title` metadata, that will always be used. So in this case, changing your article title to `<h1 data-pagefind-meta="title">Another Way to Go</h1>` this will override the automatic behavior
2. Instead, you can cut the modal out from all processing. If you add `data-pagefind-ignore="all"` to your modal, its contents will be ignored for both search indexing and metadata.

Let me know if that works out for you 🙂

**Comment by bglw** [comment]
Hi @justsilencia — I'll close this out now but let me know if you have any remaining questions
