### ISSUE TITLE
UI: Filter functionality

### ISSUE THREAD

**Issue by tenmozes** [CloudCannon/pagefind#195]
Hey, thank you for an awesome project

I have two questions regarding filters 
1. When I choose one filter, the number of search result for other shows 0 match  
2. Is it any way to change from checkbox to radio, in other words is any way to use OR logic instead of AND when you choose multiple filters? 

Legend:
Image 0 - all is fine
Image 1 - one filter is active
Image 2 - two filters are active

<img width="1095" alt="Screenshot 2023-01-13 at 7 51 32 PM" src="https://user-images.githubusercontent.com/1381404/212397103-c48abd1c-05d1-493d-8fb8-af1d9f7eecc4.png">
<img width="1064" alt="Screenshot 2023-01-13 at 7 48 48 PM" src="https://user-images.githubusercontent.com/1381404/212397116-1de45706-c9e6-4287-b906-50eb1f0bd2f9.png">
<img width="1137" alt="Screenshot 2023-01-13 at 7 50 21 PM" src="https://user-images.githubusercontent.com/1381404/212397128-c1ed2fa3-e413-4897-9942-fb5cb0a08d58.png">

**Comment by bglw** [comment]
I have a long-standing issue for an `OR` filter concept (issue #7) but that hasn't been implemented yet. Step one will be to implement some kind of API for the underlying Pagefind JS to pass an `OR` filter through, and then step two will be to add support in some way to the Pagefind UI. Nothing yet for this sorry!

> When I choose one filter, the number of search result for other shows 0 match

This is currently intentional since only `AND` filtering is supported — the numbers update to show you how many results there will be if that filter is selected (in addition to any currently selected filters)

**Comment by bglw** [comment]
I'll close this issue for now so we don't split the threads — but feel free to continue the conversation in #7 🙂

**Comment by tenmozes** [comment]
@bglw thank you for an answer
