### ISSUE TITLE
Manually defining content, without passing HTML

### ISSUE THREAD

**Issue by bakkot** [CloudCannon/pagefind#198]
I'd like to tell pagefind what the contents of my pages are directly, without having pagefind parse any HTML. Is that possible?

Specifically, I operate [logs for web platform chat rooms](https://matrixlogs.bakkot.com/). The HTML is generated by [a custom script](https://github.com/bakkot/matrix-archive-bot/blob/068e1fd9b6c4d3e94dd366a4d2d84b64a68bfbe0/render-html.js) from JSON files like [this](https://github.com/bakkot/matrix-logs/blob/master/json/WHATWG/2023-01-16.json), where each item has timestamp, author, and content. I would like to feed the timestamp/author/content into pagefind straight from the JSON; having it parse the generated HTML is a lot of unnecessary computation and also requires adding annotations to the HTML which gets served to users (or generating seperate HTML with annotations just to feed to pagefind, which is even more wasteful).

I see someone has already requested this [here](https://github.com/CloudCannon/pagefind/issues/72#issuecomment-1252321117), but I figure this warrants its own issue.

**Comment by bglw** [comment]
Hi @bakkot 👋 

This issue is also similar to #142, which dances around Pagefind dealing with JSON files directly in some way. I don't have anything to report on #142 or #72 yet, but this kind of workflow is starting to crop up here and there so it's deserving of some planning. 

No timeline on this yet, sorry, as the HTML workflow is still the primary focus for development time from my end. I'll likely drop a comment on one of those two issues if I make meaningful progress in either direction 🙂

**Comment by bglw** [comment]
Update — this will be supported via #72 which is underway — see the comment there for details 🙂

**Comment by bglw** [comment]
Hey  ! 👋

Good news — this has landed in Pagefind v1.0.0! ✨

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙

See [Indexing content using the NodeJS API](https://pagefind.app/docs/node-api/) — Specifically [index.addCustomRecord](https://pagefind.app/docs/node-api/#indexaddcustomrecord)

Let me know if you take it for a spin!
