### ISSUE TITLE
Too much disk space and bandwidth being used.

### ISSUE THREAD

**Issue by hashborgir** [CloudCannon/pagefind#221]
I'm hosting my site on a small VPS, 32GB disk space, and I can't really afford to upgrade simply because of pagefind, but check this out, something you might could look into:

11.5 GiB [##########] /_pagefind

Pagefind is taking 12GB of space and upon searching, I can see in network console that it uses megabytes worth of traffic upon each search. That's just simply too much.

Perhaps I need to optimize which pages/data I should let pagefind index. 

The site is https://www.psychedelicsdaily.com and when I type in DMT, even articles not about DMT where a DMT article is linked, also shows up in search results so I am thinking I might have to tell pagefind to avoid/ignore some recent/related articles widgets etc. and only index some stuff.

**Comment by bglw** [comment]
Hi @hashborgir 👋 

I'll take a dig — though on first look it appears that the search isn't working on your site at the moment. Is this expected?

**Comment by hashborgir** [comment]
I'm not sure something must have happened. It was working last time I checked. Sigh.

**Comment by hashborgir** [comment]
> Hi @hashborgir wave
> 
> I'll take a dig — though on first look it appears that the search isn't working on your site at the moment. Is this expected?

I had to delete some stuff and make some more room and then files got xferred and now search is functional again, but using too much bandwidth and too much disk space.

Sorry to trouble you. But I'd love to help you optimize this to be at least resource intensive as possible.

Thanks for your assistance.

**Comment by bglw** [comment]
More than happy to help there!

The first thing to look at in a setup like this is cleaning the pagefind directory between builds. Since Pagefind hashes the contents of the files is creates, changing the content of your website can change the filenames of most files within the `_pagefind` directory. If you're copying the build output onto the VPS each time, then old indexes will likely be stacking up.

The best bet there would be to delete the `_pagefind` directory first, and then copy across the new files. Let me know if that flow will work for you (or if I'm incorrect, and Pagefind is using that much disk space each and every time it runs on a fresh disk)

**Comment by hashborgir** [comment]
```
#!/bin/bash
cd /home/stoned/websites/websites/psychedelicsdaily.com-hugo
rm -rf public/
hugo -b="https://www.psychedelicsdaily.com/" --minify --ignoreCache
./pagefind_extended --source public --bundle-dir /home/stoned/websites/websites/psychedelicsdaily.com-hugo/public/_pagefind
rsync -rvazhP public stoned@t:/var/www/psychedelicsdaily.com-hugo/

```

This is my build script. I nuke the entire public dir where _pagefind is on localhost, then rsync. I will delete the _pagefind on my server as you suggest.

Now the _pagefind/ directory size is just a few megabytes. Looks like it just kept adding up over some weeks. Thanks!

**Comment by bglw** [comment]
Glad to hear — the directory should always be strictly smaller than the files it indexed, since it's a compressed version containing only the unique words.

I'll make a note to add some language to the docs around this, as users deploying in this manner will need to make sure these files don't build up over time. Glad to hear it's resolved.

Any remaining concerns around bandwidth? Doing a quick search on the site I'm seeing ~200kb which is within normal bounds

**Comment by hashborgir** [comment]
Maybe I hallucinated, haha, and saw something odd. It seems okay. I'm not sure where/how I saw a figure of 6MB but it seems fine now. Thank you.

**Comment by bglw** [comment]
Glad to hear! 🙂
