### ISSUE TITLE
Focusing the search box opens the filter panel and isn't able to be closed

### ISSUE THREAD

**Issue by zachad** [CloudCannon/pagefind#224]
In v.0.11.0, when focusing on the search box, the filter panel is shown and does not go away. Even after pressing escape to clear the search box (❤️ #124 ) the UI remains active, leaving the "drawer" element open, and the "filter" panel active. There's no way to hide them again. 

The preferred behavior was in 0.10.2: the results drawer and filter panel would also be hidden when the search input field was cleared or lost focus.

**Comment by bglw** [comment]
Hi @zachad 👋 Thanks for the report — this isn't intentional! I'll get this fixed up.

It looks like some CSS specificity changed so it's an easy fix, but I'll let things simmer for the weekend in case there are any other fixes to roll into a patch release.

For now, you could drop this CSS somewhere on your site and it will hide everything correctly 🙂
```css
.pagefind-ui__hidden {
	display: none !important;
}
```

**Comment by bglw** [comment]
I forgot to get around to releasing this sorry — now out in https://github.com/CloudCannon/pagefind/releases/tag/v0.12.0
