### ISSUE TITLE
The highlights in the results are sometimes "fuzzy" (or should I say near-matches?)

### ISSUE THREAD

**Issue by flyfoto** [CloudCannon/pagefind#231]
Example try at [my website:](https://fly-foto.de/luftbild/suche/)
Entering "rupper" results in highlights and hits for "Ruppes", "Rüppurr"
![grafik](https://user-images.githubusercontent.com/125903677/220295715-f1a5f165-fa68-4511-9804-62705f4a9570.png)
After refining the search to "ruppert" the "false" hits are gone:
![grafik](https://user-images.githubusercontent.com/125903677/220296383-97c97e0e-ba21-42e7-819f-76ffe25284b9.png)

**Comment by bglw** [comment]
Hey @flyfoto 👋 

This is intentional — Pagefind stems words and then normalizes characters. You can see a demo of the underlying stemming here: https://snowballstem.org/demo.html#German

So `rupper` gets stemmed to `rupp` based on Snowball rules, and then Pagefind matches any extensions of the word.

There isn't any existing way to configure this, except for setting [--force-language unknown](https://pagefind.app/docs/config-options/#force-language) when indexing which would disable all stemming.

What is your ideal behavior here?

**Comment by flyfoto** [comment]
Hey @bglw ,
thanks for explaining this concept and how to disable this smart hidden feature.
I am fine with it.

**Comment by flyfoto** [comment]
Word stemming in German is now much better! Together with the better ranking for exact matches the results have improvd a l lot in 1.5
