### ISSUE TITLE
Searching across all languages

### ISSUE THREAD

**Issue by marchof** [CloudCannon/pagefind#234]
Hi, first of all congratulations to this great project! I was easy to integrate with Hugo and GitHub Actions and just works. AFter using it for a while I have a  question regarding languages:

As documented only the pages with the same language than the current page are searched by PagefindUI:

> When Pagefind initializes in the browser it will check the same lang attribute and load the appropriate index.

Is there a configuration option to search across all languages and maybe have a language filter (like `data-pagefind-filter`) for the results?

Many thanks in advance!

**Comment by bglw** [comment]
Hey @marchof 👋 

No such option from the browser end of things — once the index has been split by language it would be more of a bandwidth hit to load all at once, as they each have unique metadata (and unique wasm modules)

The current answer is to use the [--force-language](https://pagefind.app/docs/config-options/#force-language) option when indexing your site, so that it _doesn't_ get split into separate languages. Then searching anywhere on the site would load the single index regardless of the lang attribute.

To add a language filter I'd look to add the attribute somewhere on each page:
```html
<body data-pagefind-filter="language:en">
 ...
```

Let me know if those paths sound viable to you 🙂

**Comment by marchof** [comment]
@bglw Thanks for the quick answer! Your explanation totally makes sense. I was already thinking about the `--force-language` option but didn't use it due to stemming. Just gave it a test run and it looks good (for en & de).

**Comment by bglw** [comment]
Awesome 🙂 Pagefind works pretty well without stemming, since it still matches extensions of words, which catches _most_ cases stemming would anyway.
