### ISSUE TITLE
Set language after pagefind has been initialized

### ISSUE THREAD

**Issue by openscript** [CloudCannon/pagefind#489]
I have a web app, where the language can be changed by the user without reloading the page. Pagefind doesn't get to know this change, so it will search in the wrong language.

Is it possible to reinitialize or change the Pagefinds language after it has been initialized?

**Comment by bglw** [comment]
Hmm, re-initializing isn't something I had considered, but I can see why it would be helpful here. I'll look at exposing something to allow this.

Part of the reason it doesn't exist is that there's a fairly high cost to doing so — not only is the index separated by language (so meta info will need to be re-fetched), the WebAssembly itself is loaded specific to a language, so re-initialization will be of the entire stack. Not necessarily a big deal, since changing language through a reload would do so anyway, but just FYI.

Will let you know when this is available!

**Comment by openscript** [comment]
@bglw Thank you so much! Not only for this, but your whole work for this project! :)

**Comment by bglw** [comment]
In either case, this has been implemented in #498 and will go out with the next release 🙂

**Comment by openscript** [comment]
> @openscript, are you using the JS search API directly, or the Default UI package?

I'm using the api and bring my own UI.

**Comment by openscript** [comment]
> In either case, this has been implemented in #498 and will go out with the next release 🙂

Thabk you so much. Looking forward trying it out!

**Comment by bglw** [comment]
Released in [v1.0.4](https://github.com/CloudCannon/pagefind/releases/tag/v1.0.4) 🎉

Let me know if that works out for you! I have also included a test specifically for you case here:
https://github.com/CloudCannon/pagefind/blob/971186cdd062995c14d2cc2bc711b09c850d086f/pagefind/features/multilingual.feature#L314-L318
