### ISSUE TITLE
"Date:" prefix in date meta data cannot be translated

### ISSUE THREAD

**Issue by WebShapedBiz** [CloudCannon/pagefind#559]
Hi.

By adding `data-pagefind-meta="date"`  to my date HTML element, the date metadata gets shown in the results prefixed with `Date:` and that particular string is not among available keys in [translations/en.json](https://github.com/CloudCannon/pagefind/blob/main/pagefind_ui/translations/en.json) therefore cannot be translated.

**Comment by bglw** [comment]
The `Date:` metadata text is just a capitalized version of the metadata tag — `data-pagefind-meta="theme"` will render in the results as `Theme:` — since these come from the content there's no easy way to universally translate these. 

Hopefully the looming modular UI will allow more custom workflows in this area.

**Comment by WebShapedBiz** [comment]
Thank you for this clarification @bglw.

**Comment by yaardie** [comment]
With Hugo SSG, you can translate the meta using i18n.
