### ISSUE TITLE
Post title displayed twice in the search results

### ISSUE THREAD

**Issue by WebShapedBiz** [CloudCannon/pagefind#562]
Hi.
This is my first go at Pagefind and everything worked well except the fact that the titles of my posts are coming twice in the search results.
My `<article>` tag has a `data-pagefind-body` tag. Under it, I have `<H1>` post title, with `data-pagefind-meta="title"`, date of publishing, and the body of an article inside a `<p>` tag. 

![scrteenshot](https://github.com/CloudCannon/pagefind/assets/6765137/1313b6da-ba26-4c4e-945d-a9bc0d3bb7af)

My problem is that I see the title twice, first as a link to the post and then as a part of the post body. Furthermore, the highlight is on the body copy of a title and not on the main title that links to the post. All that combined creates a SERP block that looks like no other I've ever seen and that's not what the UX of my visitors should be.
 
What am I doing wrong here?

Thank you for your time and effort.

CHeers.

**Comment by bglw** [comment]
Hey @WebShapedBiz 👋 

That is the default behavior of Pagefind — as the titles are auto detected from the content, it isn't removed from the content since it might be important in the sentence structure. (Technically titles are just metadata).

It's a good point though that there should be a path to change this without having to ignore the title from the index entirely. This is a good candidate for a UI option, for whether to strip the title from the content if it's a prefix. I'll look into this.

**Comment by WebShapedBiz** [comment]
Thank you @bglw for your reply.
