### ISSUE TITLE
incorrect search results for numbers

### ISSUE THREAD

**Issue by hrxkr** [CloudCannon/pagefind#702]
Pagefind Version: 1.1.1

I am getting incorrect search results for numbers. Not sure if this is a bug or a feature request for improvement. 

If num 3 is searched, it shows numbers 3, 30, 300, 3000. 
If num 30 is searched, it shows 30, 300, 3000.
If num 30000 is searched, it still shows the same result for 3000.

Similarly, if num 5 is searched it shows all the numbers starting with 5, but the second digit when added (eg 51, 52..) still it shows the same results for 5. It doesn't update to show the exact match (else number not found). 

And, if num 0 is typed it doesn't return (contains) match results. It only matches based on the first digit of the number.  

---

**Screeshots for reference**

1
<img width="858" alt="Screenshot 2024-09-08 at 4 46 05 PM" src="https://github.com/user-attachments/assets/7e80e179-b954-4c03-8a72-bc6790356a38">

2
<img width="849" alt="Screenshot 2024-09-08 at 8 01 46 PM" src="https://github.com/user-attachments/assets/aff2210c-049b-4f09-8154-39e17eddab23">

3
<img width="846" alt="Screenshot 2024-09-08 at 8 03 05 PM" src="https://github.com/user-attachments/assets/49b1ae59-2134-40bb-b07c-5fa31717495d">

**Comment by bglw** [comment]
Hi @hrxkr 👋 

Currently this behavior is expected (at least in the technical sense) due to how Pagefind operates. Everything is searched as text, and there is no special handling for numbers. 

When searching text, Pagefind searches ahead (and sometimes behind) to give better results, so in this case finding results such as "words that start with 30". This is also usually what you would want for a full text search, for example searching for `20` should give you results for `2024`, or searching ISBNs might give you useful book categorization.

What would be your ideal for the above cases? Would it be for Pagefind to only ever exact search numbers?

**Comment by hrxkr** [comment]
Hi @bglw 

Got it. Thanks for the clarification! Appreciate your detailed reply.
For my current project, text search is my primary use case so Pagefind works like a charm. 
Again, thanks to the entire team behind Pagefind for creating this fantastic product.
